SRC = source/main.cpp source/AMateria.cpp
OBJ = $(SRC:.cpp=.o)
HEADERS = headers/AMateria.hpp
NAME = interface
FLAGS= -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(OBJ)
	c++ $(FLAGS) $(OBJ) -o $(NAME)

%.o: %.cpp $(HEADERS)
	c++ $(FLAGS) -c $< -o $@

clean:
	rm $(OBJ)

fclean: clean
	rm $(NAME)

re: fclean all
